- name : Demo on Roles
  hosts :  all
  connection : local
  roles :
    - demo
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name : print URL
  hosts : all
  connection : local
  tasks :
    - name : Print URL
      ansible.builtin.debug:
        msg: URL == {{URL}}