- name: demo on condition
  hosts: all
  vars:
    a: 100
  tasks:
    - name: string conditions
      debug:
        msg: fruit name is apple
      when: fruit_name == "apple"
    - name: numerical conditions
      debug:
        msg: a is > 10
      when: a > 10