- name: read a value from parameter
  hosts: localhost
  connection: local
  pre_tasks:
    - name: install boto3
      pip:
        name: boto3
  tasks:
    - debug:
        msg: "{{ lookup('amazon.aws.aws_ssm', 'test', region='us-east-1') }}"